// <auto-generated />
using System;
using FitnessTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Api.Migrations
{
    [DbContext(typeof(FitnessTrackerDbContext))]
    [Migration("20260821215637_SeedBuiltInExercises")]
    partial class SeedBuiltInExercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FitnessTracker.Api.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredDistanceUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredWeightUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.BodyMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("BodyFatPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAtUtc");

                    b.ToTable("BodyMeasurements", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipment")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryMuscleGroup")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name", "IsArchived");

                    b.ToTable("Exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Barbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Barbell Bench Press",
                            PrimaryMuscleGroup = "Chest",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Barbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Incline Barbell Bench Press",
                            PrimaryMuscleGroup = "Chest",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Dumbbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Dumbbell Bench Press",
                            PrimaryMuscleGroup = "Chest",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Dumbbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Incline Dumbbell Bench Press",
                            PrimaryMuscleGroup = "Chest",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Barbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Overhead Press",
                            PrimaryMuscleGroup = "Shoulders",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Dumbbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Dumbbell Shoulder Press",
                            PrimaryMuscleGroup = "Shoulders",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Dumbbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Lateral Raise",
                            PrimaryMuscleGroup = "Shoulders",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Cable",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Cable Fly",
                            PrimaryMuscleGroup = "Chest",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Bodyweight",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Push-Up",
                            PrimaryMuscleGroup = "Chest",
                            TrackingType = "RepsOnly"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Cable",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Triceps Pushdown",
                            PrimaryMuscleGroup = "Triceps",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Cable",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Overhead Triceps Extension",
                            PrimaryMuscleGroup = "Triceps",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Barbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Back Squat",
                            PrimaryMuscleGroup = "Quadriceps",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Barbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Front Squat",
                            PrimaryMuscleGroup = "Quadriceps",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Barbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Romanian Deadlift",
                            PrimaryMuscleGroup = "Hamstrings",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Barbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Deadlift",
                            PrimaryMuscleGroup = "Back",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Machine",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Leg Press",
                            PrimaryMuscleGroup = "Quadriceps",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Dumbbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Bulgarian Split Squat",
                            PrimaryMuscleGroup = "Quadriceps",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Dumbbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Walking Lunge",
                            PrimaryMuscleGroup = "Quadriceps",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Machine",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Leg Extension",
                            PrimaryMuscleGroup = "Quadriceps",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Machine",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Leg Curl",
                            PrimaryMuscleGroup = "Hamstrings",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000021"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Machine",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Standing Calf Raise",
                            PrimaryMuscleGroup = "Calves",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000022"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Bodyweight",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Pull-Up",
                            PrimaryMuscleGroup = "Back",
                            TrackingType = "RepsOnly"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000023"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Bodyweight",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Chin-Up",
                            PrimaryMuscleGroup = "Back",
                            TrackingType = "RepsOnly"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000024"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Cable",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Lat Pulldown",
                            PrimaryMuscleGroup = "Back",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000025"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Barbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Barbell Row",
                            PrimaryMuscleGroup = "Back",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000026"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Cable",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Seated Cable Row",
                            PrimaryMuscleGroup = "Back",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000027"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Dumbbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "One-Arm Dumbbell Row",
                            PrimaryMuscleGroup = "Back",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000028"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Cable",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Face Pull",
                            PrimaryMuscleGroup = "Shoulders",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000029"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Barbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Barbell Curl",
                            PrimaryMuscleGroup = "Biceps",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000030"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Dumbbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Dumbbell Curl",
                            PrimaryMuscleGroup = "Biceps",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000031"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Dumbbell",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Hammer Curl",
                            PrimaryMuscleGroup = "Biceps",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000032"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Bodyweight",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Plank",
                            PrimaryMuscleGroup = "Core",
                            TrackingType = "Duration"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000033"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Bodyweight",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Hanging Leg Raise",
                            PrimaryMuscleGroup = "Core",
                            TrackingType = "RepsOnly"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000034"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Cable",
                            ExerciseType = "Strength",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Cable Crunch",
                            PrimaryMuscleGroup = "Core",
                            TrackingType = "WeightAndReps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000035"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "None",
                            ExerciseType = "Cardio",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Outdoor Run",
                            PrimaryMuscleGroup = "Full Body",
                            TrackingType = "DistanceAndDuration"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000036"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Treadmill",
                            ExerciseType = "Cardio",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Treadmill Run",
                            PrimaryMuscleGroup = "Full Body",
                            TrackingType = "DistanceAndDuration"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000037"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Bicycle",
                            ExerciseType = "Cardio",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Cycling",
                            PrimaryMuscleGroup = "Legs",
                            TrackingType = "DistanceAndDuration"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000038"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Stationary Bike",
                            ExerciseType = "Cardio",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Stationary Bike",
                            PrimaryMuscleGroup = "Legs",
                            TrackingType = "DistanceAndDuration"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000039"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Rowing Machine",
                            ExerciseType = "Cardio",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Rowing Machine",
                            PrimaryMuscleGroup = "Full Body",
                            TrackingType = "DistanceAndDuration"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000040"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Elliptical",
                            ExerciseType = "Cardio",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Elliptical",
                            PrimaryMuscleGroup = "Full Body",
                            TrackingType = "DistanceAndDuration"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000041"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "Stair Climber",
                            ExerciseType = "Cardio",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Stair Climber",
                            PrimaryMuscleGroup = "Legs",
                            TrackingType = "Duration"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000042"),
                            CreatedAtUtc = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Equipment = "None",
                            ExerciseType = "Cardio",
                            IsArchived = false,
                            IsCustom = false,
                            Name = "Walking",
                            PrimaryMuscleGroup = "Full Body",
                            TrackingType = "DistanceAndDuration"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkoutType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StartedAtUtc");

                    b.ToTable("Workouts", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("WorkoutExercises", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("REAL");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Rpe")
                        .HasColumnType("REAL");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("REAL");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId", "SetNumber")
                        .IsUnique();

                    b.ToTable("WorkoutSets", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.BodyMeasurement", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.ApplicationUser", "User")
                        .WithMany("BodyMeasurements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Exercise", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.ApplicationUser", "CreatedByUser")
                        .WithMany("CustomExercises")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Workout", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.ApplicationUser", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutExercise", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Api.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutSet", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.WorkoutExercise", "WorkoutExercise")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.ApplicationUser", b =>
                {
                    b.Navigation("BodyMeasurements");

                    b.Navigation("CustomExercises");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutExercise", b =>
                {
                    b.Navigation("WorkoutSets");
                });
#pragma warning restore 612, 618
        }
    }
}
